<?xml version="1.0"?>
<robot name="kitchen" 
    xmlns:xacro="http://www.ros.org/wiki/xacro">

    <xacro:macro name="kitchen" params="prefix parent model *origin">

        <!-- Kitchen Details -->
        <xacro:property name="kitchen_length_electrolux" value="2.44"/>
        <xacro:property name="kitchen_width_electrolux" value="1.082"/>
        <xacro:property name="kitchen_height_electrolux" value="0.89599"/>
        <xacro:property name="kitchen_length_aurora" value="2."/>
        <xacro:property name="kitchen_width_aurora" value="1.2"/>
        <xacro:property name="kitchen_height_aurora" value="1.1"/>

        <xacro:if value="${model == 'electrolux'}">
            <xacro:property name="kitchen_length" value="${kitchen_length_electrolux}"/>
            <xacro:property name="kitchen_width" value="${kitchen_width_electrolux}"/>
            <xacro:property name="kitchen_height" value="${kitchen_height_electrolux}"/>
        </xacro:if>
        <xacro:unless value="${model == 'aurora'}">
            <xacro:property name="kitchen_length" value="${kitchen_length_aurora}"/>
            <xacro:property name="kitchen_width" value="${kitchen_width_aurora}"/>
            <xacro:property name="kitchen_height" value="${kitchen_height_aurora}"/>
        </xacro:unless>

        <!-- Kitchen -->
        <link name="${prefix}kitchen">
            <visual>
                <geometry>
                    <mesh filename="package://robot_kitchen_description/meshes/kitchen_${model}.stl"/>
                </geometry>
            </visual>
            <!--
            <collision>
                <origin xyz="${kitchen_length/2.} ${-kitchen_width/2.} ${-kitchen_height/2.}" rpy="0 0 0"/>
                <geometry>
                    <box size="${kitchen_length} ${kitchen_width} ${kitchen_height}"/>
                </geometry>
            </collision>
            -->
        </link>

        <!-- Reference -->
        <link name="${prefix}kitchen_reference"/>

        <!-- Parent to Kitchen -->
        <joint name="${parent}to_kitchen" type="fixed">
            <xacro:insert_block name="origin"/>
            <parent link="${parent}"/>
            <child link="${prefix}kitchen"/>
            <xacro:insert_block name="origin"/>
        </joint>

        <!-- Kitchen to Reference -->
        <joint name="${prefix}kitchen_to_kitchen_reference" type="fixed">
            <parent link="${prefix}kitchen"/>
            <child link="${prefix}kitchen_reference"/>
            <origin xyz ="0 ${-0.13-0.207/2.} 0" rpy="0 0 0"/>
        </joint>
    </xacro:macro>
</robot>
